### ISSUE TITLE
Email addresses not recognized

### ISSUE THREAD

**Issue by hometm** [steven-elliott/vcard-json#1]
Hello, 

email address with the following prefix "item1" are not recognized.
item1.EMAIL;type=INTERNET;type=pref:a@b.c
This entry was found in my vCard file (V3.0, exported by Mac Contacts) 

Some entries are in this format. These entries are working.
EMAIL;type=INTERNET;type=WORK;type=pref:c@d.e

Is there a bugfix planned?

Tobias

**Comment by steven-elliott** [comment]
Hey Tobias, I'll take a look and push an update.

**Comment by steven-elliott** [comment]
New update pushed [0.4.0](https://github.com/steven-elliott/vcard-json/tree/0.4.0)

**Comment by hometm** [comment]
thank you, now it works

Tobias
