### ISSUE TITLE
Reading vcf failed

### ISSUE THREAD

**Issue by hometm** [steven-elliott/vcard-json#2]
Hello, 

I received a Outlook generated vCard file (see listing down, can't attach a file to this issue).  The file was generated and not modified manually. This file is a small export of a large Outlook database. vcard-json isn't able to read this file.

But:
- Windows 7 (without Office) isn't able to open this file (error message: does not seem to be a valid vcard file)
- Mac OS can open this file, but can't find any vCard inside

Do you think, that this file can be managed by vcard-json?

###################
BEGIN:VCARD
VERSION:3.0
N:Mustermann;Hubert;;;
FN:Mustermann Hubert
TEL;type=HOME;type=pref:069123456
EMAIL;type=INTERNET;type=pref:hubert.mustermann@web.de
END:VCARD
###################

Tobias

**Comment by steven-elliott** [comment]
Hey Tobias, I just tested the sample you posted and it worked fine. Do you have a sample output that is failing?

**Comment by hometm** [comment]
Hi, 

Could it be an encoding orline break issue? Unfortunatelly, I can't attach the file (even as txt) to this issue.

the exception happens in line "_.each(attributes, function(attribute){" :

2015-09-28 11:17:59.060  - error: TypeError: Cannot set property 'fullname' of undefined
    at EventEmitter.attributeMatched (c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\lib\vcard-json.js:72:24)
    at EventEmitter.emit (events.js:118:17)
    at c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\lib\vcard-json.js:45:12
    at Function._.each._.forEach (c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\node_modules\underscore\underscore.js:158:9)
    at c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\lib\vcard-json.js:40:7
    at Function._.each._.forEach (c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\node_modules\underscore\underscore.js:153:9)
    at parseVcard (c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\lib\vcard-json.js:23:5)
    at c:\Program Files\ioBroker\node_modules\iobroker.vCard\node_modules\vcard-json\lib\vcard-json.js:61:26
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by steven-elliott** [comment]
It could be a line break issue, but it's hard to say for certain without having a test case. The actual error is from line:72 due to the contact object being undefined:

`contact.fullname = s(line.slice(3)).clean().value();`

This means it's not recognizing the start of the file where it declares the beginning of the vcard:

`BEGIN:VCARD`

I should clean that up but that won't solve your current problem. 

Did you try dragging the text file directly into this comments section?

**Comment by hometm** [comment]
Hi, 

sending per github comment didn’t work. I’ll try it in this way



Tobias

**Comment by steven-elliott** [comment]
Not seeing anything. You can find my contact info here and send the text via email - http://stevenelliott.me/

**Comment by steven-elliott** [comment]
Fixed in [v0.4.1](https://github.com/steven-elliott/vcard-json/tree/v0.4.1)
