### ISSUE TITLE
parseVcard: Exception

### ISSUE THREAD

**Issue by hometm** [steven-elliott/vcard-json#3]
Hi, 

by using parseVcard together with the well known Outlook-vcf file, I'll get an exception ("undefined is not a function", "TypeError"). Saving the xmlHttp.responseText to a file, and reading via parseFile works.

my code:
 var xmlHttp=new XMLHttpRequest();
 xmlHttp.open('GET',adapter.config.vcardPath, false );
 xmlHttp.send(null);

 if(!xmlHttp.responseText) {
     //...
       return;
        }
   vcards= vcard.parseVcard(xmlHttp.responseText); //here the Exception occures

Do you have an idea?

**Comment by steven-elliott** [comment]
Can you paste the stack trace so I can the line where the error occurs?

**Comment by hometm** [comment]
solved, see pull request 
Tobias
