### ISSUE TITLE
No comment about many  warnings at README

### ISSUE THREAD

**Issue by ppKrauss** [steven-elliott/vcard-json#7]
Using UBUNTU 16 LTS, after `npm install vcard-json`

```
/home/user/SANDBOX/contacts
└─┬ vcard-json@0.5.1 
  ├── underscore@1.8.3 
  └─┬ underscore.string@3.3.4 
    ├── sprintf-js@1.0.3 
    └── util-deprecate@1.0.2 

npm WARN enoent ENOENT: no such file or directory, open '/home/user/SANDBOX/contacts/package.json'
npm WARN contacts No description
npm WARN contacts No repository field.
npm WARN contacts No README data
npm WARN contacts No license field.
```

Seems a kind of **(minor) installation bug**.

**Comment by steven-elliott** [comment]
If you are creating a new project you'll want to run 'npm init' in the new directory before running 'npm install'. This way you'll have a package.json file created and your project will be created. This isn't specific to vcard-json.
